### ISSUE TITLE
Use downlit

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3gallery#99]
Not sure what would be required to make this work. Should also be used in the book.

https://github.com/r-lib/downlit

**Comment by be-marc** [comment]
downlit syntax highlighting and auto linking in multi line code boxes can be activated in the YAML section.


```
highlight_downlit: true
```
I will activate this in #102.

downlit + distill does not auto link inline code but this works

````r
`r downlit::autolink("mlr3::Learner")`
````

We should stick to `mlr3book::ref()` because it allows us to have an alternative link text and the `mlr3::` can be omitted.
